@startchen

entity reservation{
    id <<key>>
    screening_id <<FK>>
    created_at
    reservation_status
}

entity reservation_screening_seats{
    reservation_id <<FK>>
    screening_seat_id <<FK>>
}

entity movies{
    id <<key>>
    title
    genre
    description
    duration
}

entity screening{
    id <<key>>
    movies_id <<FK>>
    cinema_room_id
    screening_date
    price
    time_slot
    start_time
    end_time
}

entity payment{
    id <<key>>
    reservation_id <<FK>>
    amount
    payment_status
    payment_method
}

entity cinemaRoom{
    id <<key>>
    roomNumber
    rows
    rowCapacity
    capacity
}

entity tickets{
    id <<key>>
    reservation_id <<FK>>
    ticket_number
    ticket_status
    date_issued
}

entity seats{
    id <<key>>
    cinemaRoom_id <<FK>>
    rowNumber
    seatNumber
}

entity screening_seats{
    id <<key>>
    screening_id <<FK>>
    seats_id <<FK>>
    screeningSeatStatus
}

relationship reservationSeats{
}

reservation =(n,1)= screening
reservation =1= payment
reservation =1= tickets
reservation =(1,n)= reservation_screening_seats
screening_seats =(1,n)= reservation_screening_seats

screening =(n,1)= movies
screening =(1,n)= screening_seats

cinemaRoom =(1,n)= seats
seats =(1,n)= screening_seats

@endchen
