name: cinema-booking-system

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: cinema-booking-system
    depends_on:
      - postgres
    env_file:
      - ../.env
    ports:
      - "8080:8080"

  postgres:
    image: postgres:17
    container_name: db-cinema
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "54431:5432"
    volumes:
      - cinema_postgres_data:/var/lib/postgresql/data

volumes:
  cinema_postgres_data: