@startuml
left to right direction

actor "Customer" as customer
actor "Staff" as staff
actor "Admin" as admin

admin --|> staff

rectangle "Cinema Booking System" {
  usecase "Create Account" as UC1
  usecase "Login" as UC2
  usecase "Browse Screenings" as UC3
  usecase "View Free Seats" as UC4
  usecase "Create Reservation" as UC5
  usecase "View Reservation" as UC6
  usecase "Cancel Reservation" as UC7

  usecase "Manage Movies" as UC8
  usecase "Manage Screenings" as UC9
  usecase "Manage Reservations" as UC10
  usecase "Complete Payment/Mark as Paid" as UC11
  usecase "Complete Refund" as UC12
  usecase "Validate Ticket" as UC13
  usecase "Expire Tickets" as UC14
  usecase "Browse Movies" as UC15
  usecase "Filter Movies" as UC16
  usecase "View Movie Details" as UC17

  usecase "Manage Cinema Rooms" as UC18
}

customer --> UC1
customer --> UC2
customer --> UC3
customer --> UC4
customer --> UC5
customer --> UC6
customer --> UC7

staff --> UC3
staff --> UC4
staff --> UC5
staff --> UC6
staff --> UC7
staff --> UC8
staff --> UC9
staff --> UC10
staff --> UC11
staff --> UC12
staff --> UC13
staff --> UC14
staff --> UC15
staff --> UC16
staff --> UC17

admin --> UC18


@enduml
