@startuml
left to right direction

actor "Customer" as customer
actor "Staff" as staff
actor "Admin" as admin

admin --|> staff

rectangle "Cinema Booking System" {
  usecase "Create Account" as UC1
  usecase "Login" as UC2
  usecase "Browse Movies" as UC3
  usecase "Filter Movies" as UC4
  usecase "View Movie Details" as UC5
  usecase "Browse Screenings" as UC6
  usecase "View Free Seats" as UC7
  usecase "Create Reservation" as UC8
  usecase "View Reservation" as UC9
  usecase "Cancel Reservation" as UC10

  usecase "Manage Movies" as UC11
  usecase "Manage Screenings" as UC12
  usecase "Manage Reservations" as UC13
  usecase "Complete Payment" as UC14
  usecase "Complete Refund" as UC15
  usecase "Validate Ticket" as UC16
  usecase "Expire Tickets" as UC17

  usecase "Manage Cinema Rooms" as UC18
}

customer --> UC1
customer --> UC2
customer --> UC3
customer --> UC4
customer --> UC5
customer --> UC6
customer --> UC7
customer --> UC8
customer --> UC9
customer --> UC10

staff --> UC3
staff --> UC4
staff --> UC5
staff --> UC6
staff --> UC11
staff --> UC12
staff --> UC13
staff --> UC14
staff --> UC15
staff --> UC16
staff --> UC17

admin --> UC18

UC8 ..> UC7
UC8 ..> UC14
UC10 ..> UC15

@enduml
